version: "3"

services:
  shop:
    build: .
    ports:
      - 8080:80
    restart: always
    environment:
      - ConnectionStrings__ShopDatabase=Server=<adress>;Port=5432;Database=shop_db;User Id=<username>;Password=<password>;
      - STRIPE__PUBLIC_KEY=
      - STRIPE__SECRET_KEY=
      - PORT=80
      - Authentication__Google_ClientId=
      - Authentication__Google_ClientSecret=

      - Email__Host=
      - Email__Port=
      - Email__SenderName=
      - Email__SenderEmail=
      - Email__Account=
      - Email__Password=
      - Email__Security=

      - S3StorageSettings__AccessKey=
      - S3StorageSettings__Bucket=
      - S3StorageSettings__RootPath=
      - S3StorageSettings__SecretKey=
      - S3StorageSettings__Server=
      
      - HostSettings__Host=
      - HostSettings__Scheme=https